#!/bin/bash

source conf/contrast_play_variables.sh

    bash contrast_play_save_svs_to_tiles.sh 0 1 &

NUMBER_OF_TILES=$(find ${EXPERIMENT_DIR} -name *${TILE_SIZE}.png | wc -l)  # USING ${TILE_SIZE} as all files generated by save_svs_to_tiles.py have this in their filenames (and there are other irrelevant files in the PATCH_PATH directory)
echo "START.SH: INFO: total number of tiles = " ${NUMBER_OF_TILES}
